set xlabel 'seconds'
set ylabel 'packets/s'
set style fill solid
set term png enhanced font 'Verdana,10'
set output 'plot.png'
set title "Protocol breakdown in the last hour"
plot "arp.data" using 1:($2/60) smooth csplines title "ARP" \
     ,"icmp.data" using 1:($2/60) smooth csplines title "ICMP" \
     ,"tcp.data" using 1:($2/60) smooth csplines title "TCP" \
     ,"udp.data" using 1:($2/60) smooth csplines title "UDP"

